insert into ideas (title, description) values ('#Hypertriangle connected Sheffield to Leeds and Manchester £1.8 billion','');
insert into ideas (title, description) values ('','Create a 365 date/ year festival environment');
insert into ideas (title, description) values ('','better connectivity for the whole city region free wifi');
insert into ideas (title, description) values ('','full city region super fast broadband');
insert into ideas (title, description) values ('','international food and drink festival like Cannes is to film');
insert into ideas (title, description) values ('','more cycle specific infrastructure (European style) not mixed with traffic');
insert into ideas (title, description) values ('','permanent start up hub located in the heart of the city');
insert into ideas (title, description) values ('10,000 council houses','');
insert into ideas (title, description) values ('100% Renewable energy','100% renewable energy');
insert into ideas (title, description) values ('365-day Festival programme','Instigate a 365-day festival programme, with music/film/arts/literature,etc. events schedules every day, including Christmas day Tramlines');
insert into ideas (title, description) values ('3D printed organism-inspired buildings','');
insert into ideas (title, description) values ('A 100-foot tall Henderson''s relish bottle in the city centre','');
insert into ideas (title, description) values ('A TED talk every day of the year - everyone here gives or hosts a TED talk - open to all - every day','');
insert into ideas (title, description) values ('A city of little Sheffields ','A neighbourhood level economic development planning/ strategy');
insert into ideas (title, description) values ('A city that goes for International Awards','');
insert into ideas (title, description) values ('A greener city','Connect the peaks, the moorland, the bogs, the rural parks & have a whole visitor strategy/ experience - which is sold internationally');
insert into ideas (title, description) values ('A rethink of exisitng policy','Reuse empty building - with a focus on art space - temporary ''pop-up'' for temporary impact - tax incentive for property owner');
insert into ideas (title, description) values ('A ring of maker hubs on the city centre outskirts','');
insert into ideas (title, description) values ('A river of beer flowing through the city, with stainless steel banks','');
insert into ideas (title, description) values ('Abolish love Leeds','');
insert into ideas (title, description) values ('Abolish ofsted','Abolish ofsted to increase the confidence of schools and teachers');
insert into ideas (title, description) values ('Access to funds','Agency to simplify access to funds and business support');
insert into ideas (title, description) values ('Actually finishing the retail centre in Sheffield (24hr City).  Ensure retail quarter dovetails into living/ leisure space','');
insert into ideas (title, description) values ('Adult education programme','Adult education programme led by the businesses - inspirational/aspirational. The Sheffield ''TED'', ''The City Learning of All''');
insert into ideas (title, description) values ('Advanced manufacturing centre hold open evenings/ art performances/ talks and/ or comes to city centre to do these','');
insert into ideas (title, description) values ('Affordable Infrastructure','Free parking and/or subsidised bus and train to a greater extent. Digital infrastructure cheap/free for all business');
insert into ideas (title, description) values ('Affordable space for musicians and creatives','Space should be protected from gentrification. Include practice rooms, incubation and rehearsal spaces to create the next generation of musical stars');
insert into ideas (title, description) values ('Affordable/free creche','');
insert into ideas (title, description) values ('After school/weekend clubs','Keep yound adults and children off the streets');
insert into ideas (title, description) values ('Agency for start-ups','Agency for start-ups with implementation procedures');
insert into ideas (title, description) values ('All organisations in Sheffield hold networking events- bringing sectors together to discuss an issue (and drink local beer!)','');
insert into ideas (title, description) values ('Alternative energy','More use of solar and wind power to develop alternative power technologies');
insert into ideas (title, description) values ('An effective leader of the region','Promoting Sheffield as a capital for creativity and innovation');
insert into ideas (title, description) values ('An independent body to accelerate delivery of the AID (not AMID)','Properly funded');
insert into ideas (title, description) values ('An independent planning organisation','To create a dynamic city centre which will ?? all that''s good about Sheffield to attract visitors and people to live and work here');
insert into ideas (title, description) values ('Annual Sheffield carnival','Showcase talent, products, arts and youth');
insert into ideas (title, description) values ('Annual music award/commission','New Sheffield composer creates a unique performance for Sheffield audiences. Musician retains rights and makes a living through live performances. Different style of music every year');
insert into ideas (title, description) values ('App to see where taxes are spent','');
insert into ideas (title, description) values ('Appreciative Inquiry training for citizens','Appreciative Inquiry for all citizens to re-imagine city centre');
insert into ideas (title, description) values ('Apprenticeship capital of Europe','');
insert into ideas (title, description) values ('Archetecture competition','Open architecture competition for key new builings');
insert into ideas (title, description) values ('Arts spaces','Integration of arts and culture into public spaces');
insert into ideas (title, description) values ('Aspire to 2nd qtr education','Work with head teachers to buy in to #vibrantsheffield for the long-term');
insert into ideas (title, description) values ('Attract new business to Sheffield','Attract new business to Sheffield');
insert into ideas (title, description) values ('Attract world championships to Sheffield','');
insert into ideas (title, description) values ('Attracting London talent ','Aggressively market in London to bring business and talent to the region');
insert into ideas (title, description) values ('Avenue to zero','Avenue to zero');
insert into ideas (title, description) values ('Awards Ceremony','Host major awards ceremony - BAFTAs, Grammys, etc. to really put the city region on the map');
insert into ideas (title, description) values ('Basic income for everyone','Basic income for everyone');
insert into ideas (title, description) values ('Basic income for start-ups','Small business start-up pay (like basic income)');
insert into ideas (title, description) values ('Be the greenest city in the world','');
insert into ideas (title, description) values ('Beehives','Beehives on every building in Sheffield');
insert into ideas (title, description) values ('Beer Museum','Beer Museum');
insert into ideas (title, description) values ('Befriending services','Eliminate lonliness with befriending services');
insert into ideas (title, description) values ('Better communication on city website','Communication - better website than ''Welcome to Sheffield''');
insert into ideas (title, description) values ('Better communication','Better communication and advertising about existing opportunities in Sheffield');
insert into ideas (title, description) values ('Better cycling routes','');
insert into ideas (title, description) values ('Big Biz, Little Biz','Established businesses offer outreach support to start up / early businesses ');
insert into ideas (title, description) values ('Big sister/ brother scheme','Matching disadvantaged kids with an older person who will take them for ice cream (etc) every now and then and be a mentor/sonding board/big sibling');
insert into ideas (title, description) values ('Bike Letting Service','Bike letting service (Boris bikes)');
insert into ideas (title, description) values ('Bike Scheme for Sheffield','');
insert into ideas (title, description) values ('Bike lanes','Better bikes lanes and motorised Boris bikes');
insert into ideas (title, description) values ('Bike racks','Buses and trams with bike racks');
insert into ideas (title, description) values ('Brand Sheffield','');
insert into ideas (title, description) values ('Brand Sheffield','Develop and invest in a strong Sheffield brand campaign - the worlds best village / the big small city');
insert into ideas (title, description) values ('Brand as Outdoor City','Branding ourselves as the outdoor city - promoting outdoor living as a Festival City - festival of food, music, art');
insert into ideas (title, description) values ('Bring Tour de Yorkshire to Sheffield','');
insert into ideas (title, description) values ('Bring new organisations to Sheffield','Build a target audience of organisations we want to be in Sheffield and then paln of attack.');
insert into ideas (title, description) values ('Bring the HQ of the FA to the home of Sheffield','');
insert into ideas (title, description) values ('Build family homes and social infrastructure in the city centre','');
insert into ideas (title, description) values ('Build national arts centre','');
insert into ideas (title, description) values ('Buildings for Startups','Use empty buildings for business start up');
insert into ideas (title, description) values ('Business Investment','Local powers to set taxes/business investment');
insert into ideas (title, description) values ('Business Tinder','Speed dating / mentoring / matching big businesses with small ');
insert into ideas (title, description) values ('Business hubs to allow collaboration','');
insert into ideas (title, description) values ('Business incubators for young people','Incubators for all types of biz that are connected to the education system so young people are more aware of entrepreneuership pathways');
insert into ideas (title, description) values ('Business trips','Open up our business centres to schools and organise tourist trips to businesses in the region');
insert into ideas (title, description) values ('Businesses / School collaboration','Getting more businesses involved with schools. Industries leading education. Emergent industries, not the usuals. On a Sheffield wide scale. In every school');
insert into ideas (title, description) values ('Buy local campaign','Support local businesses to create local jobs (buy local campaign)');
insert into ideas (title, description) values ('COOP Community Brewery','Cooperative community brewery, learn, create recipes, promote, distribute');
insert into ideas (title, description) values ('Cable Cars','Cable cars from hill to hill and city centre');
insert into ideas (title, description) values ('Cable cars',' cabe cars down the river Don');
insert into ideas (title, description) values ('Cable-cars to and from each of the 7 hills','');
insert into ideas (title, description) values ('Café culture in city centre','Pedestrianisation of the entire city centre to create an outdoor café culture, with public lectures on street corners');
insert into ideas (title, description) values ('Café culture','');
insert into ideas (title, description) values ('Capped working hours','Capped working hours - everyone leaves to spend time with families and do hobbies');
insert into ideas (title, description) values ('Capped working hours','Capped working hours');
insert into ideas (title, description) values ('Car Share lanes','Car share - can use bus lanes');
insert into ideas (title, description) values ('Care of old people','Place greater value on care of old people');
insert into ideas (title, description) values ('Care provider wages','Lobby Care providers to pay living wage');
insert into ideas (title, description) values ('Careers advice for young people','Careers advice: life skills from primary school age upwards, eg. interview skills, life pathways');
insert into ideas (title, description) values ('Cashless transport','Full oyster card system for Sheffielf public transport, no having t ochoose daily/weekly pass, carry cash etc');
insert into ideas (title, description) values ('Cental area for Arts','Central area for Arts');
insert into ideas (title, description) values ('Central transport hub','Bring main transport into central hub and build a proper distribution/connectivity across the region');
insert into ideas (title, description) values ('Centre for Circular Economy','Circular economy = no waste, using recycling, using every part of manufacturing');
insert into ideas (title, description) values ('Centre of Pipecleaner Excellence','');
insert into ideas (title, description) values ('Centres of collaboration','Develop centres of collaboration based on critical / emerging sectors and technologies');
insert into ideas (title, description) values ('Change education outcome measures','Changing outcome measures for education system');
insert into ideas (title, description) values ('Change the name of SCR','Sheffield City Region to become Republic of…');
insert into ideas (title, description) values ('City Centre Expo','Create City Centre expo');
insert into ideas (title, description) values ('City Centre Wifi','City Centre Wifi');
insert into ideas (title, description) values ('City Centre Wifi','Implement City Centre Wifi ');
insert into ideas (title, description) values ('City Centre ideas wall - write you ideas here!','');
insert into ideas (title, description) values ('City Centre innovation district','');
insert into ideas (title, description) values ('City Centre regeneration','Build a proper city centre! Make the design for the Retail Quarter a reality');
insert into ideas (title, description) values ('City Region Council procurement collaboration','Where possible, ask for BS11000 to promote collaboration on all contracts with the Council');
insert into ideas (title, description) values ('City Region outcome measures','Creating new city region outcome measures: happiness index, wealth distribution, diversity, creativity measure');
insert into ideas (title, description) values ('City of culure','SCR-City of culture joining our comms');
insert into ideas (title, description) values ('City wide street art policy','Establish city wide street art policy to enable much wider enjoymenet & participation in street art');
insert into ideas (title, description) values ('Close/Sell Meadowhall','Close/Sell Meadowhall');
insert into ideas (title, description) values ('Collaboration Expo','Start collaboration expo');
insert into ideas (title, description) values ('Communal libraries and workspaces','Develop more communal libraries and work spaces');
insert into ideas (title, description) values ('Communicating Sheffields plan','Marketing campaign for Sheffield which clearly communicates us and what we are and what we want to do');
insert into ideas (title, description) values ('Community Action Days','Days where businesses in the area come together with communities to clean up / improve area');
insert into ideas (title, description) values ('Community Allotments','Community Allotments - sharing ownership - use disused land');
insert into ideas (title, description) values ('Community Benefit Agreements','City region wide');
insert into ideas (title, description) values ('Community Owned City','Community owned city - explore ways in which public and private assets can be transferred into public ownership. Sheffield Bond issue to invest in community resources.');
insert into ideas (title, description) values ('Community food production co-operatives','Maintaining land through food production in the local community');
insert into ideas (title, description) values ('Community gardens/unused green spaces and allotments','');
insert into ideas (title, description) values ('Community involvement in city planning','Participative planning process in how city region, and in particular, the mayor, operates. People at heart of holistic planning for future.');
insert into ideas (title, description) values ('Community time banking','Community time banking');
insert into ideas (title, description) values ('Compulsory e-voting','');
insert into ideas (title, description) values ('Compulsory school age work experience','Gives the chance for young adults and employers to work with one another');
insert into ideas (title, description) values ('Concert Hall','Build a state of the art concert hall with digital / disabled facilities unrivaled in the uk. Should be modern, gorgeous, light fulled with outstanding community-education space/programme');
insert into ideas (title, description) values ('Concert hall 800 capacity','City Hall is disfunctional too big for most');
insert into ideas (title, description) values ('Conferences','16-18 conference every year. Sixth formers / colleges / apprenticeships etc. to shape the future of their city');
insert into ideas (title, description) values ('Connect Schools/Business','Connect schools to business in a way that both access the benefits');
insert into ideas (title, description) values ('Connect Sheffield Underground within city','Sheffield Underground to connect within and without the city');
insert into ideas (title, description) values ('Connection to Doncaster Airport','Real connectivity within region to the airport');
insert into ideas (title, description) values ('Considering Social Values','Consider social values when deciding on public sector/corporate contracts ');
insert into ideas (title, description) values ('Copy Berlin''s regeneration ideas','Go to Berlin & copy their ideas for regeneration being led by cultural & artistic sector');
insert into ideas (title, description) values ('Corridor from/to Rotherham','Better use of the canal to create another corridor from/to the city and Rotherham to help ease congestion');
insert into ideas (title, description) values ('Council documents to be written in verse','All council documents to be written in verse');
insert into ideas (title, description) values ('Council members with business background','X% of council members from business - council needs to appreciate the role of businesses');
insert into ideas (title, description) values ('Create a City Myth','Create a myth to drive tourism our way');
insert into ideas (title, description) values ('Create a ''tech centre''','Use empty industrial building to being to creat a new world centre for tech UK''s silicon valley');
insert into ideas (title, description) values ('Create more open spaces in the East','Give the East access to everything that the West has');
insert into ideas (title, description) values ('Creating the belief culture that we are the best','Creating the belief culture that we are the best');
insert into ideas (title, description) values ('Creative/innovation programme','Introduce a creative and extra-curricular programme for creativity and innovation');
insert into ideas (title, description) values ('Cross generational city living','Ravey davy Retirement Home. Cross generational city  living; Sheffield as ''Home'' for all');
insert into ideas (title, description) values ('Crowd funding to build social projects','Like the Retail Quarter');
insert into ideas (title, description) values ('Cultural Discount Scheme','All residents/employees of the region are entitled to discounts at theatres and events');
insert into ideas (title, description) values ('Cultural festival ','Cultural festival celebrating the contribution of all our communities engaging international partners');
insert into ideas (title, description) values ('Cycle lane','Sheffield - Abbeydale -Peak district cycle lane (off road)');
insert into ideas (title, description) values ('Cycle points','Cycle points across te city, bike racks everywhere (currently there are none in Peace Gardens)');
insert into ideas (title, description) values ('Cycle programme','Cycle to help those who are lonely or isolated. Reducing loneliness whilst getting fit');
insert into ideas (title, description) values ('Cycling City','Turn Sheff. into a cycling city. Ski lifts for cyclists');
insert into ideas (title, description) values ('Decent restaurants in city','');
insert into ideas (title, description) values ('Dedicated Export Site','Dedicated Export Site for Sheffield Products');
insert into ideas (title, description) values ('Degree content driven by industry need','Universities talk to business/industry to develop course content - so students graduate with skills that are needed and will get them jobs - BUT - with business/industry contributing and developing new models of delivering degrees etc');
insert into ideas (title, description) values ('Deregulation of governance','Radical Deregulation of governance of our city (link with creating and commitments to own it). Take functions currently delivered by council and pass them down (ot across ) to other parties.');
insert into ideas (title, description) values ('Destination Sheffield','Promoting Sheffield as a weekend break destination');
insert into ideas (title, description) values ('Develop Sheffield as atourist and events destination in conjunction with Peak District and use crowd funding to attract events','');
insert into ideas (title, description) values ('Develop a see'' thee app that tells people what Sheffield has to offer','');
insert into ideas (title, description) values ('Develop train infrastructure','Making use of and developing the existing train structure');
insert into ideas (title, description) values ('Develop ways to store electricity','');
insert into ideas (title, description) values ('Development corporation','Similar to Docklands to stimulate growth');
insert into ideas (title, description) values ('Devolution','Real devolution - no strings attached');
insert into ideas (title, description) values ('Devolved Social/Fiscal Powers','');
insert into ideas (title, description) values ('Different meet-ups for different industries/groups with common interests','');
insert into ideas (title, description) values ('Digital Infrastructure','Create free/cheap quick digital infrastructure for all business');
insert into ideas (title, description) values ('Digital connectivity','Invest in the digital connectivity in region. Ensure the whole region can engage (and work) digitally, removing need to travel in region');
insert into ideas (title, description) values ('Digitally controlled environments for healthcare','Health & Wellbeing: growing high protein food on the flatlands. Digitally controlled environments in unification with Sheffield Hallam healthcare agenda');
insert into ideas (title, description) values ('Disruptive leader','Disruptive leader at the top');
insert into ideas (title, description) values ('Driverless transportation system 24/7','');
insert into ideas (title, description) values ('EX charging ','at all SCC Owned car parking spaces');
insert into ideas (title, description) values ('Eco friendly new builds','Rules for all new buildings to be eco-green builds to solidify our position as a socially orientated, green city.');
insert into ideas (title, description) values ('Education of past/present Sheffield to inspire','Inspire pride in Sheffield through educating everyone about the past (what was achieved) and the future (what will be achieved), eg. facts/signs to inform passers by.');
insert into ideas (title, description) values ('Electric cars for emergency','Electric cars for emergency');
insert into ideas (title, description) values ('Electrionic transport agenda','Create an electric transport agenda');
insert into ideas (title, description) values ('Embedded apprenticeships','Embedd apprenticeships throughout the region - all business to take on placement, whether they are long term work placements or not. Volunteer or paid to give opportunities and experience');
insert into ideas (title, description) values ('Employment intermediaries','For specialist sectors / SCR');
insert into ideas (title, description) values ('Empty office space for start-ups','New businesses to be able to use empty office space for free');
insert into ideas (title, description) values ('Engage business in community','Get our big business employers to become engaged in making Sheffield a better place');
insert into ideas (title, description) values ('Engaging local news','The local papers provide spuport to publicise good, local news stories for small organisations');
insert into ideas (title, description) values ('Enterprise villages','Living space above offices in city regions of regeneration. Create buildings where you live above offices to create an enterprise community');
insert into ideas (title, description) values ('Entrepeneur clinic','Entrepeneur clinic where people business ideas can discuss ideas to plan how to make ideas into reality. Something like a ''nice'' dragon''s den mentoring idea');
insert into ideas (title, description) values ('Environmental roofs','All roofs should be green and solar');
insert into ideas (title, description) values ('European centre for materials testing','Create a European Centre for materials testing and research to boost advanced manufacture');
insert into ideas (title, description) values ('Eurpoean City of Culture','Keep applying');
insert into ideas (title, description) values ('Evening coffee service','Coffee in the evening');
insert into ideas (title, description) values ('Exciting elections','Making the mayoral elections exciting so people vote');
insert into ideas (title, description) values ('Exhibition centre','New exhibition centre');
insert into ideas (title, description) values ('Expand Higher Apprenticeships','Expand Higher Apprenticeships');
insert into ideas (title, description) values ('Expanded city centre retail','Make the city centre retail quarter take precedence over Meadowhall expansion');
insert into ideas (title, description) values ('Expanded tram network','Tram network expanded to west and south Sheffield');
insert into ideas (title, description) values ('Extend Super Tram','');
insert into ideas (title, description) values ('Extended tram service','Tram extended to Rotherham and Doncaster and Bamsley to help meet aim of low carbon city centres and reduce congestion, enhace a=social movility and inclusion');
insert into ideas (title, description) values ('Extension of tram','Extension of tram city/region wide - full connectivity');
insert into ideas (title, description) values ('Extra Curricular programme','Introduction of ''Extra-Cirricular'' programme for creativity of innovation for schools');
insert into ideas (title, description) values ('Ey up'' square','Ey up'' square - a public space for celebration of success');
insert into ideas (title, description) values ('Fail Space','Fail space - a space to allow businesses to try an idea without fear of failure');
insert into ideas (title, description) values ('Faster, cheaper transport over City Region','Public Transport over valleys, not just between them, making it faster, chepaer, and easier to get around Sheffield (around the city, not just through it)');
insert into ideas (title, description) values ('Festival of innovation','City centre festival of innovation - take over the city centr. Parties & DJs at night, companies and exhibits during the day');
insert into ideas (title, description) values ('Festival of street art','Sheffield international festival of street art - Kid Acne etc');
insert into ideas (title, description) values ('Festival of the Outdoors','Festival of the outdoors celebrating all aspects of our link to the outdoors across the city');
insert into ideas (title, description) values ('Figurehead for Sheffield City Region','Figurehead for Sheffield City Region - spokesperson for the region (non-political), advocate, sell Sheffield Region, shout from the rooftops re the benefits');
insert into ideas (title, description) values ('Financial incentives to retain students in Sheffield','');
insert into ideas (title, description) values ('First city to implement citizen wages','');
insert into ideas (title, description) values ('Football museum','Sheffield "Birthplace of Football" Museum');
insert into ideas (title, description) values ('Free Broadband','Fast,free broadband for all');
insert into ideas (title, description) values ('Free Childcare','Free childcare for everyone');
insert into ideas (title, description) values ('Free University Places for Sheffield kids','');
insert into ideas (title, description) values ('Free business rates for a year ','');
insert into ideas (title, description) values ('Free car parking for green cars','?');
insert into ideas (title, description) values ('Free city centre parking','');
insert into ideas (title, description) values ('Free city centre wifi','Free city centre wifi');
insert into ideas (title, description) values ('Free ice cream in city centre','');
insert into ideas (title, description) values ('Free internet access','For the whole of the city region, like York');
insert into ideas (title, description) values ('Free milkshakes in the city centre every Friday, to bring all the boys (and girls) to the  yard','');
insert into ideas (title, description) values ('Free start up facilities for a year','');
insert into ideas (title, description) values ('Free transport for under 18s','Across the entire region on all public transport. If not free, then outrageously cheap');
insert into ideas (title, description) values ('Free wine and beer and wifi for whole city region','');
insert into ideas (title, description) values ('Free/more apprenticeships ','');
insert into ideas (title, description) values ('Freedom for Social Clubs','Prompte greater freedom for social clubs in both schools and for the elderly (at the same time), sports clubs and religious groups');
insert into ideas (title, description) values ('Fusion energy','Fusion! or increasing focus on advanced technologies and renewable energy. Sheffield invents + develop nuclear fusion');
insert into ideas (title, description) values ('Gateway to the North','Selling the idea of the ''gateway to the north'' to business, tourists, students. Use council funds and a ''gateway to the North'' group of influential Sheffield business');
insert into ideas (title, description) values ('Get council technology into 21st Century','');
insert into ideas (title, description) values ('Get rid of bus lanes','');
insert into ideas (title, description) values ('Giant Zipwire from Peaks to Town','');
insert into ideas (title, description) values ('Give away a work space','Give away a live-work space in sheffield a year. Run a competition for progressive social business ideas. Attract young, ambitious & diverse businesses. Advertise alternative routes to young people. Create meaningful jobs');
insert into ideas (title, description) values ('Give up a supper seat','Give up a supper seat');
insert into ideas (title, description) values ('Gold Suburbs','Concentrate on people in the community - create gold suburbs');
insert into ideas (title, description) values ('Governmnt Funding for Tech','Major Government funding for tech');
insert into ideas (title, description) values ('Grad showcase','Grad showcase - so you want to work for an entrepreneur? Sheffield''s group businesses engage with the universities and local milk round');
insert into ideas (title, description) values ('Grant Thornton opens up its new office to different innovation events every evening','');
insert into ideas (title, description) values ('Grass Roots ideas funding throughSheffield Soup','105 neighbourhoods x 12 - 1260 ideas funded - £630K local people ');
insert into ideas (title, description) values ('Grass over carparks at AMRC','');
insert into ideas (title, description) values ('Great Sheffield Run','');
insert into ideas (title, description) values ('Green -only housing','New housing to be green-only');
insert into ideas (title, description) values ('Green Investment Funds','Advanced and sustainable green investment funds');
insert into ideas (title, description) values ('Green Roofs Mandate','Mandate green roofs for all new buildings');
insert into ideas (title, description) values ('Groups of specialists that collaborate to drive innovation, and champion the region. i.e. tech, green tech, shop keepers, steel workers designers, brewers, etc, etc','Everyone who works in a ''skilled'' industry or everyone');
insert into ideas (title, description) values ('Guaranteed employement for any graduate 2:1 and above in a business/organisation in the city ','');
insert into ideas (title, description) values ('HR train to airports','');
insert into ideas (title, description) values ('Halo'' courses','Halo'' courses');
insert into ideas (title, description) values ('Heritage walks','Heritage walks - colour coded - around city (like Boston) that encouratges walking and discovery of our cultural assets aka breweries ');
insert into ideas (title, description) values ('Higher ''arts'' institutions - drama schools, art facilities ','');
insert into ideas (title, description) values ('Host awards in Sheffield ','Get BBC to give us hosting of something like BAFTAs');
insert into ideas (title, description) values ('Host the greatest exhibition of the north','Do it the Sheffield Way');
insert into ideas (title, description) values ('Housing co-operatives for students','HAs, students and developers funding co-operative purchase of premises');
insert into ideas (title, description) values ('Hs2 in city centre','');
insert into ideas (title, description) values ('Hubs for Change','Enabiling our mini villages as hubs for change - vibrancy');
insert into ideas (title, description) values ('Hydrogen vehicles','Hydrogen vehicles to reduce emmissions. If we convert buses, taxis, HGVs to hydrogen then air quality issues in area resolved. Also, it''s made in Sheffield');
insert into ideas (title, description) values ('Hyper loop','Hyper loop');
insert into ideas (title, description) values ('Hyperlink Pioneers','The city that trials hyperlink in Europe');
insert into ideas (title, description) values ('Hyperloop Pilot ','Set up hyperloop pilot with Elon Musk connecting Sheffield North and South');
insert into ideas (title, description) values ('Hypertube','Get the hypertube on the agenda');
insert into ideas (title, description) values ('IP bids','Joint IP bids with industry, encourage more to keep IP in the region ');
insert into ideas (title, description) values ('Ideas stock exchange','People can float their ideas on the exchange and people can bid for them. The idea owners would post details of their ideas & social media updates etc. The price will go up &down at some point they''ll sell the idea and go and work with the highest biider');
insert into ideas (title, description) values ('Improve transport links','improve transport links (south of city). Park and ride for cars.');
insert into ideas (title, description) values ('Incentivise wellness','Companies to incentivise wellness in employees');
insert into ideas (title, description) values ('Inclusion','Reinvigorate community centres to help channel / change Sheffields insulated groups - employment');
insert into ideas (title, description) values ('Increase tourism offer','Get key attractions to more people out of peaks into city');
insert into ideas (title, description) values ('Increasing participation in healthy activities','');
insert into ideas (title, description) values ('Incredible edible Sheffield - edible plants on  every bit of spare ground','');
insert into ideas (title, description) values ('Independent Trader Relief','Relief, support and space for independent traders in the city centre');
insert into ideas (title, description) values ('Independent shopps in Castlegate','Castlegate - galleries, indie shopping, bars, green space');
insert into ideas (title, description) values ('Indoor space for art','Indoor space for art -A city centre free space for creativity');
insert into ideas (title, description) values ('Indoor space for talking and collaborating','Indoor space for talking and collaborating');
insert into ideas (title, description) values ('Innovation museum','Build a hands-on innovation museum to create inspiration and tourist destination');
insert into ideas (title, description) values ('Innovation pathway','Innovation pathway - a connected approach (incubators, service & support); an established jouney and network so all Sheffielders can test and grow innovatgive ideas. Connected to education system so Sheffield can grow up as part of the innovation pathway.');
insert into ideas (title, description) values ('Innovative structures','Experiment with new and mixed business models for public services and spaces and transport');
insert into ideas (title, description) values ('Install solar power on flat roofs','Install solar panels on all flat roofs owned by the council, starting with the Landsdowne Estate');
insert into ideas (title, description) values ('Inter company collaboration','Promoting and facilitating cooperation between companies');
insert into ideas (title, description) values ('Interest free loans to buy bikes ','');
insert into ideas (title, description) values ('International Conference Centre','');
insert into ideas (title, description) values ('International Festival','');
insert into ideas (title, description) values ('International Schools Festival','International schools festival in Sheffield ');
insert into ideas (title, description) values ('Investment in Manufacturing','More investment in manufacturing techniques and solutions to support SMEs');
insert into ideas (title, description) values ('Involve everyone in policy','Everyone in policy/politics/education and a placement in industry');
insert into ideas (title, description) values ('Job Swap','Job swap city wide - anyone to try a new job for a day');
insert into ideas (title, description) values ('Job centre','Rebrand job centre - change who manages it, what does, eg. shop with hag a UBI and no job centre in SCR');
insert into ideas (title, description) values ('Job matching site','Like a dating site but aimed at jobs and candidates');
insert into ideas (title, description) values ('Joining East/West Sheffield to achieve better ''access for all'' ','Joint projects for young people on ''neutral'' territory');
insert into ideas (title, description) values ('Keep in touch with Sheffield','Harness the diaspora (eg ex-Sheffield graduates who leave) and keep them up to date with everything in Sheffield to either tempt them back and/or use them as advocates');
insert into ideas (title, description) values ('Kids Soup','Kids Soup - young people to share their ideas on an ideas stock exchange and other to contribute to making them happen. Make them realise there is more to life than law, accountacy, medicing. Funding available');
insert into ideas (title, description) values ('Knowledge Hubs','Meeting online or face to face, to look at things like networking, sharing knowledge, training, best practice');
insert into ideas (title, description) values ('Legalisiation of cannabis production/consumption','Allow PCC to make laws through the devolution deal');
insert into ideas (title, description) values ('Library Renovation','Renovate the central library + other iconic buildings, beautiful 30s building, café. Make it a great place to go. Make it a vibrant library.');
insert into ideas (title, description) values ('Light Night','Huge inspiring installations around the city');
insert into ideas (title, description) values ('Link between education and business needs','Educational courses linked into business requirements; encouragement of young people to take risks & be entrepreneurial');
insert into ideas (title, description) values ('Link businesses and schools','Links between businesses & schools i.e. venture matrix - projects, curriculum, mentors');
insert into ideas (title, description) values ('Live Arts Centre','A live arts centre for small scale touring');
insert into ideas (title, description) values ('Live Lab for school children','');
insert into ideas (title, description) values ('Live screen in city centre','Live Screen in the city centre to promote events eg. screens on parkway');
insert into ideas (title, description) values ('Local Food sourcing/buying','Local food sourcing and networks - buy more local food, areas to plant and grow, sell in shops ''buy to local'' made easier');
insert into ideas (title, description) values ('Local Investment Bank','% of profits invested into start ups, tax incentives, mentoring');
insert into ideas (title, description) values ('Local Sustainable Energy','Find local ways to develop local and sustainable energy');
insert into ideas (title, description) values ('Local agriculture','Free up a % of council owned park + agricultural land to be used for local food production');
insert into ideas (title, description) values ('Local currency for skills and service','Create a local currency for trading skills and services');
insert into ideas (title, description) values ('Local currency','Sheffield £ - local currency / spend locally');
insert into ideas (title, description) values ('Local happiness register','Create a local happiness register');
insert into ideas (title, description) values ('Local papers to publish ''good news'' stories','Local papers encouraged to have a ''good news'' section each day, with the public allowed to/encouraged to contribute');
insert into ideas (title, description) values ('Look at planning conflict and reducing it','');
insert into ideas (title, description) values ('Lottery to fund public ideas','Sheffield lottery to fund the curation of public ideas');
insert into ideas (title, description) values ('Low carbon food production','utilise the district heat network to provide low, cost heat for production of insects for food, which then feed fish, fish feeds plants (and humans) etc');
insert into ideas (title, description) values ('Lower business rates','Offer lower business rates for first 2 years to every start-up');
insert into ideas (title, description) values ('Lower town centre rents and rates','Lower town centre rents and rates/rent caps');
insert into ideas (title, description) values ('Major tech conference','Sheffield should host a major tech conference');
insert into ideas (title, description) values ('Make Sheffield a media centre','');
insert into ideas (title, description) values ('Man of Steel'' on peaks','Sculpture or statue on peaks pointing to Sheffield (with a family?)');
insert into ideas (title, description) values ('Manufactoring park','An advances manufactoring park - focused more on innovators + start-ups. Encouraging them to cross-pollinate ideas + skills');
insert into ideas (title, description) values ('Maps/tourist info','Maps and tourist info; newsagents with info/leaflets');
insert into ideas (title, description) values ('Marketing Hub Sheffield','Marketing Hub Sheffield - a group of consultants from different marketing areas who will collaborate with start ups and charities');
insert into ideas (title, description) values ('Marketing for the city ','Independent marketing for the city, overseen by a consortium. Dynamic, vibrant, irresistible');
insert into ideas (title, description) values ('Marketplace','High street artisanal development. Young people and entrepreneurs partner with the market leaders to create high street offers');
insert into ideas (title, description) values ('Measuring everything different','Measure everything different: schools, economy, everything');
insert into ideas (title, description) values ('Mentor','all young people to have a mentor of older age (could be complex)');
insert into ideas (title, description) values ('Mentoring youth','Entrepreneurship/Confidence and mentoring in confederated and consisent models across schools and colleges - create a more bespoke curriculum. ');
insert into ideas (title, description) values ('Mentorship program ','network for older people to mentor start ups');
insert into ideas (title, description) values ('Mentorship program','provide a mentor for every person who wants to start their own business + access to free advice on tax, liabilities');
insert into ideas (title, description) values ('Merge the Universities','');
insert into ideas (title, description) values ('Merge the football clubs','');
insert into ideas (title, description) values ('Metal recycling to create a giant gate to the North','police, the people, artists, designers & makers');
insert into ideas (title, description) values ('Michellin Star Restaurant','3 Michelin star restaurant - we need to provide aspirational catering options in the city and a real destination for visitors');
insert into ideas (title, description) values ('Micro brewery','Micro brewery beer tasting every Monday for free (or pay what you can)');
insert into ideas (title, description) values ('Monthly festival','A festival every month celebrating a strenght of the city region');
insert into ideas (title, description) values ('More Uber cabs','');
insert into ideas (title, description) values ('More artists in the city','Attracting artists on the exodus out of London. London specific marketing campaign. Attracting artists to inhabit old buildings by removing red tape');
insert into ideas (title, description) values ('More family friendly bars','');
insert into ideas (title, description) values ('More green areas','Create more green areas in the city - gardens, vegetable plots, open green spaces - link a route through Sheffield city centre to the peak distict for walkers');
insert into ideas (title, description) values ('More home working','Incentive more home working');
insert into ideas (title, description) values ('More public toilets','');
insert into ideas (title, description) values ('More public toilets','Every new building to provide a public toilet that they have to maintain');
insert into ideas (title, description) values ('More renewable energy','Extend the district heating system; take more people out of fuel poverty; more renewable energy');
insert into ideas (title, description) values ('More soup/ bigger spoons','More cash injection/funding and rewards');
insert into ideas (title, description) values ('Much bigger outdoor music thing','');
insert into ideas (title, description) values ('N/A','Arts council, EU, City Region');
insert into ideas (title, description) values ('National Expo','National Expo and build a multi functional expo space');
insert into ideas (title, description) values ('National Marketing Campaign for Sheffield','As a centre of excellence');
insert into ideas (title, description) values ('National level museum (eg football - tourism, destination)','');
insert into ideas (title, description) values ('New accoustic music venue','A new accoustic music venue');
insert into ideas (title, description) values ('New arrivals platform','A platform to support new arrivals - people or business - to integrate into the community, find premises, staff + network. It will make Sheffield an even more attractive place to set up');
insert into ideas (title, description) values ('New green spaces in the city centre for people to meet and exercise','');
insert into ideas (title, description) values ('New larger one selling local work as well','Arts council, EU  ');
insert into ideas (title, description) values ('New tram line','Tram to Dore via Heeley + Meersbrook');
insert into ideas (title, description) values ('Nigel Knowles ','Nigel Knowles to sell the services of Sheffield PLC.');
insert into ideas (title, description) values ('No strings attached start up pot ','No strings attached start up pot - cash incentive eg space on from soup - move to stew');
insert into ideas (title, description) values ('Offer a bike to every employee in Sheffield for £50 to use fo work - a healthy workforce is a more effective workforce','');
insert into ideas (title, description) values ('Online highstreet','Global Shopping - online highstreet, link to the real highstreet');
insert into ideas (title, description) values ('Opera in city centre','Opera in the city centre/peace gardens');
insert into ideas (title, description) values ('Outdoor Sports Festival','');
insert into ideas (title, description) values ('Outdoor visual arts programme','Massive visual arts programme - art galleries ''inside out.'' More Andrew Motion on outisde of buildings, etc');
insert into ideas (title, description) values ('Oyster Card','Oyster card for Sheffield city region on trams, buses and trains');
insert into ideas (title, description) values ('Parkour Championships ','');
insert into ideas (title, description) values ('Pedestrianise city centre','Pedestrianize city centre - inner area of 2 sq miles. Not just shops, but also mixed tenure and residences with families living in city centre.');
insert into ideas (title, description) values ('People want to do more than just shop - turn the High Street into a cultural centre - bars, cafs, theatres, gigs','Local Govt - deregulate the High Street & increase opportunities for cafes and bars; entrepreneausre - open up pop up restaurants, bars, gigs, space; cap the cost of the street');
insert into ideas (title, description) values ('Place for positive news stories','Process, forum or place for all sectors to publicise (local & nationally) good news stories from the city at accessible cost');
insert into ideas (title, description) values ('Playground for grown ups','');
insert into ideas (title, description) values ('Policy on Independent Shops','Policy on independent shops - % in the city, encourage them to be in Sheffield and succed, independent shops quarter, alternative high street');
insert into ideas (title, description) values ('Porgramme of events in city centre','');
insert into ideas (title, description) values ('Principality Sheffield','Declare Sheffield as a principality');
insert into ideas (title, description) values ('Progressive Education Centre','New progressive education centre or template - create independent non-private schooling system, new ways to lern math + english + draw on Sheffield for being different');
insert into ideas (title, description) values ('Promote Sheffield as City of Innovation','');
insert into ideas (title, description) values ('Promotions Website','Promo website/PR Mechanism');
insert into ideas (title, description) values ('Prototyping capital of Europe','');
insert into ideas (title, description) values ('Public Decision Making','Expanded role in public decision making');
insert into ideas (title, description) values ('Public involvement in decentralising','Expanded role for public in decentralising');
insert into ideas (title, description) values ('Public lectures in open-spaces','Public lectures in all city centre open-spaces at least once a day');
insert into ideas (title, description) values ('Public space for artists','local artists are offered public space for iconic art installations');
insert into ideas (title, description) values ('Public toilets','');
insert into ideas (title, description) values ('Public transport from city centre to advanced manufacturing centre - to promote better links','');
insert into ideas (title, description) values ('Public transport needs joining up','');
insert into ideas (title, description) values ('Publicising where we are great eg, flow etc - Great Sheffield businesses ','');
insert into ideas (title, description) values ('Quality of Life Exchange','Older experienced person gives up hours for younger trainers resulting in fewer working hours and longer training period.');
insert into ideas (title, description) values ('Rate relief for start ups','?');
insert into ideas (title, description) values ('Re-scheme Education','VAK testing for kids'' styles');
insert into ideas (title, description) values ('Refurbing Abandoned Housing','');
insert into ideas (title, description) values ('Regenerate East End','Regenerate East End - mixed living - and encourage cultural and artistic performers to relocate');
insert into ideas (title, description) values ('Regenerate East End/Tinsley','Regenerate East End/Tinsley with mixed tenure, business, and living accommodation');
insert into ideas (title, description) values ('Regenerate Gateways into Sheffield','Gateways into Sheffield need to be regenerated & imaginative - symbolising what the city stands for');
insert into ideas (title, description) values ('Regional Football Tournament ''Sheffield World Cup''','Sheffield, Barnsley, Rotherham, Chesterfield, Doncaster, etc. ');
insert into ideas (title, description) values ('Regional IP Hub','Regional IP Hubs - Keeping IP in Sheffield');
insert into ideas (title, description) values ('Regional collaboration','More collaboration between Northern city regions');
insert into ideas (title, description) values ('Regional identity','Plan and market Sheffield under the same identity & narrative to promote one image for Sheffield to the outside world');
insert into ideas (title, description) values ('Regional marketing fund','Set up a regional fund to market internationally Sheffield City region');
insert into ideas (title, description) values ('Regular Vibrant Events','Vibrant Inquiry events each year + ability to measure success and change');
insert into ideas (title, description) values ('Remote health consultations','Health consultations using modern tech');
insert into ideas (title, description) values ('Remove N/S Borders of UK','Review all maps of UK so that N/S doesn''t exist and only compass point is C = Centre - Sheffield');
insert into ideas (title, description) values ('Remove traffic lights on Brookhill roundabout','');
insert into ideas (title, description) values ('Renewable energy company','Our own renewable energy company that provides energy across the city with our own grid - wind & water - selling into the national grid');
insert into ideas (title, description) values ('Rent-a-gran','Grannies and Grandpas can babysit and keep mums and dads in work');
insert into ideas (title, description) values ('Reopen Ski Village','');
insert into ideas (title, description) values ('Respected science, arts and culture festival','A globally admired and respected science, arts and culture festival');
insert into ideas (title, description) values ('Rethink the political hierarchy ''lord mayor'' and similar posts','');
insert into ideas (title, description) values ('Riverside Culture','Create a riverside culture in Sheffield - cafes, walkways, boats, clear the rubbish, etc. Shortcuts throughout the city');
insert into ideas (title, description) values ('Rolling art installations','Rolling art plynth sites in city and region that accepts art. Constantly moving from site to site, allowing locals to see a wide range of creativity');
insert into ideas (title, description) values ('School Leaver Programmes','Promotion of alternative routes into work in schools through employers going into schools and educating the skills they look for - tell school kids about school leaver programmes!');
insert into ideas (title, description) values ('School for entrepreneurs','Incubator for anyone leaving Sheff. univeristy (or schools)');
insert into ideas (title, description) values ('Schools/camps for community relationships','Summer Schools and/or camps for building new relationships in communities with businesses and creative people');
insert into ideas (title, description) values ('Sculptures of men marching to peaks','');
insert into ideas (title, description) values ('Sensory mental health centre','Mental health centre: a sensory environment created to aid mental health and well-being and alleviate criminality ');
insert into ideas (title, description) values ('Set up a centre for city-region innovation, advising other city regions on how to innovate','');
insert into ideas (title, description) values ('Set up enterprise zones','For digital small start ups rather than manufacturing. Do it internally, not on brownfield sites. Fit out warehouses instead');
insert into ideas (title, description) values ('Shared economy','Sharing economy on a city scheme, eg. AirBNB with everything else');
insert into ideas (title, description) values ('Shared office space between firms','Shared office spaces between multiple firms to inspire collaboration');
insert into ideas (title, description) values ('Shared responsibility of city powers','Transfer more powers around planning, regulation, etc from the local autorities to a group of ''change agents'' who can work within sector values but do the right thing for the city - create ''shared responsibility.'' trust & deregulation of public services');
insert into ideas (title, description) values ('Sheffield Airport - not Robin hood!','');
insert into ideas (title, description) values ('Sheffield Beer Distribution Company','Sheffield Beer Distribution Company - global of Sheffield microbreweries (SIBA?)');
insert into ideas (title, description) values ('Sheffield Benefit Scheme','Sheffield Bene Scheme');
insert into ideas (title, description) values ('Sheffield City Region Careers Advice Service ','Career Pathway - Future Pathways');
insert into ideas (title, description) values ('Sheffield Crowd Fund','Crowdfunding, kickstarter, peer to peer lending is increasing. Can we create our own? Sheffield funders for Sheffield businesses ');
insert into ideas (title, description) values ('Sheffield Employment Year','Every young person does one year of employment on subsidised wage');
insert into ideas (title, description) values ('Sheffield Expo','Sheffield Expo or similar');
insert into ideas (title, description) values ('Sheffield FC','Combine united & Wednesday to a superclub called Sheffield FC - THE oldest football club in the world');
insert into ideas (title, description) values ('Sheffield Funding Circle','Crowd Funding Circle, Not for profit org re-investing returns to local economy, available to companies in City Region');
insert into ideas (title, description) values ('Sheffield Hub','For intereted parties to contribute and share ideas. Create a public business');
insert into ideas (title, description) values ('Sheffield Innovation Prize','200,000 biannual prize and mentoring competition for high-value innovation');
insert into ideas (title, description) values ('Sheffield Living Wage','Make the Sheffield Living wage higher than the National Living Wage');
insert into ideas (title, description) values ('Sheffield Oyster card','Oyster card connecting all trames, buses, trains etc - plus improved routes');
insert into ideas (title, description) values ('Sheffield Parliament','Sheffield Parliament. Sheffield currency to implement');
insert into ideas (title, description) values ('Sheffield Pound','Sheffield Pound. Telepresence portals, mobility (could be ski lift connecting hills of Sheffield), free wifi, Sheffield oyster card');
insert into ideas (title, description) values ('Sheffield as a beautiful city','Making Sheffield a beautiful city');
insert into ideas (title, description) values ('Sheffield crowdfunding ','Sheffield people investing in Sheffield businesses and Sheffield innovation ');
insert into ideas (title, description) values ('Sheffield ideas platform','Platform to connect and share ideas in Sheffield - we want everyone to be part of the conversation - young people have ideas and so much to offer but don''t know where to start and who to talk to. They need to be able to voice what they want to do + other people can contribute finding the solutions');
insert into ideas (title, description) values ('Sheffield''s prominence in the world','Establish Sheffield''s place in the world - be at all of the big business festivals in the world.');
insert into ideas (title, description) values ('Sheffiield Portal','Portal for facts / stats about Sheffield so everyone can be ambassadors');
insert into ideas (title, description) values ('Shops open later in city centre','Later opening of restaurants and shops in city centre');
insert into ideas (title, description) values ('Showcase Sheffield region ','Based on UKDTI inside enterprise initiative');
insert into ideas (title, description) values ('Skills swap','Skill-swap.com - barter system');
insert into ideas (title, description) values ('Smart transport','Reducing congestion, Traffic controls, Cars talking to traffic systems, link train and tram');
insert into ideas (title, description) values ('Snooker Halls','Snooker halls (exemplify world class) Snooker programme to keep it here');
insert into ideas (title, description) values ('Social Innovation UTC','?');
insert into ideas (title, description) values ('Social/Financial reform','Demand social and financial reform');
insert into ideas (title, description) values ('Spaces for start-ups','Empty offices offered to start-ups');
insert into ideas (title, description) values ('Sport / recreation centres of excellence across the region','Put in centres to celebrate geography: canoeing centre, cycling trails, rock climbing');
insert into ideas (title, description) values ('Stainless steel statue of Richard Hawley outside the station','');
insert into ideas (title, description) values ('Start up centre','Start up centre for retailers - like the corn exchange in Leeds. A start up for smaller retailers to try on their ideas, how to cost rents, short leases and lots of events to bring people in, tied-ins with small business advice group help');
insert into ideas (title, description) values ('Start up hubs','');
insert into ideas (title, description) values ('Start-up cluster','Communal workspaces - office space that can be hired by the hour or day for start-ups, next to other start-ups to allow for collaboration');
insert into ideas (title, description) values ('Steel family ','To go with the man of steel to represent city aspirations');
insert into ideas (title, description) values ('Steel statues beside the railway','Steel statues beside the railway');
insert into ideas (title, description) values ('Subsidised bars','');
insert into ideas (title, description) values ('Supermarkets to sell imperfect produce','Lobby supermarkets to sell their wonky fruit and vegetables');
insert into ideas (title, description) values ('Supertrain','Supertrain using tram train technology');
insert into ideas (title, description) values ('Support for fathers looking after their children','Support for men taking time out of work to look after kids - marketing camoaign for male CEOs (etc) to show example by going P/T or taking plenty of leave when their kids are young - showing that it''s ok!');
insert into ideas (title, description) values ('Take the city off grid ','Generate our own power');
insert into ideas (title, description) values ('Tax breaks for education','Tax breaks for companies who let employees work in schools');
insert into ideas (title, description) values ('Teaching Technology in Schools','Teach the use of technology in schools - kids want technology to tell them what to do, but don''t understand how it works');
insert into ideas (title, description) values ('Teaching life skills in schools','Teach life skills/financial awareness in schools');
insert into ideas (title, description) values ('Telepresence units to overseas cities','Give overseas cities a glimpse of Sheffield and encourage a fun reason to come to the city');
insert into ideas (title, description) values ('Tell people about Sheffield','Tell people about Sheffield!');
insert into ideas (title, description) values ('The Accessible City','Not just ramps, but connecting culture, business, sharing interests');
insert into ideas (title, description) values ('The Star content','The Star to have a good news page');
insert into ideas (title, description) values ('There''s a city directory of every voluntary group and its events/ activities that anyone can access - build cohesive communities','');
insert into ideas (title, description) values ('Train to Dore','');
insert into ideas (title, description) values ('Training co-operative','Sharing knowledge & ideas across companieseg tech training, sharing business ''lessons learned'' how to source a website succesfully…By Sheffield businesses, for sheffield businesses!');
insert into ideas (title, description) values ('Tram extension','Extrend tram train to other outlying areas of the city region to the north of the city. Need better connection to city centre 1 hour not acceptable.');
insert into ideas (title, description) values ('Tram','Silent, electric, automatic. To connect the city centre to other areas of the region such as the AMID and beyond');
insert into ideas (title, description) values ('Transport update','Simple regional public transport alternative to or better bus system');
insert into ideas (title, description) values ('Tunnel to Manchester','');
insert into ideas (title, description) values ('Twin Cities','Make more use of twinned international cities');
insert into ideas (title, description) values ('Underground rail links','Create an integrated infrastructure/land plan for the whole city region (move the parkway underground/underground rail links)');
insert into ideas (title, description) values ('Universal 5G','Universal 5G connectivity');
insert into ideas (title, description) values ('Universities engaging with SMEs and wider community and supporting local R&D','');
insert into ideas (title, description) values ('Universities open on IP','Universities to be more open on IP');
insert into ideas (title, description) values ('University funding for applied research','');
insert into ideas (title, description) values ('Upskill at any age','Upskill at any age');
insert into ideas (title, description) values ('Urban Gardening','Old derilect land turned into city farms - guerilla gardening of public spaces');
insert into ideas (title, description) values ('Use empty retail space for start-ups','Empty retail spaces used proactively for start-ups and SMEs to access the market whilst promoting enterprise and retail.');
insert into ideas (title, description) values ('Use empty shops to sell local goods','Emtpy shops used as places for ''the makers'' to sell goods - make Sheffield known for independent shops, food outlets, cafes');
insert into ideas (title, description) values ('VAK learning systems','VAK learing styles - schools');
insert into ideas (title, description) values ('Vibrant Investment','More vibrant investment approach that can be accessible to start ups');
insert into ideas (title, description) values ('Vibrant city centre which attracts business as well as social visitors, does not have to conflict with retail at meadow hall but have its own attraction/ pull','');
insert into ideas (title, description) values ('Viewing platform','Sheffield viewing platform. A high, permanent viewing platform to view the landscape of the city. Perhaps a wind turbine');
insert into ideas (title, description) values ('Virgin Space Flight','Virgin Space Flight from Don / Sheff airport');
insert into ideas (title, description) values ('Vocational education that''s relevant to the new world','');
insert into ideas (title, description) values ('Walking / Cycling paths','Walkways / cycling paths / small roads (not highways) that connect all the neighborhoods around the city rather than everything going in / out');
insert into ideas (title, description) values ('Weather proofing streets','Weather proofing city centre streets');
insert into ideas (title, description) values ('Weekly Festivals','A festival every week. Help Sheffield become known as the ''festival city'' and attract tourism');
insert into ideas (title, description) values ('Winter Gardens Extension','Extension to Winter Gardens - more city centre indoor');
insert into ideas (title, description) values ('Winter Gardens Sun','Artificial sun in the Winter Gardens');
insert into ideas (title, description) values ('Work experience fair','Esnrue young people have opportunity to see breadth of opportunity available in sheffield and are given opportunities to try out different jobs -all key sectors-big businesses and SMEs to be involved');
insert into ideas (title, description) values ('Worlds biggest climbing wall','Worlds biggest climbing wall');
insert into ideas (title, description) values ('Wrap around care for free at schools ','');
insert into ideas (title, description) values ('Year-round festival events','Held bank  holidays, new year. August - keep the spirit alive and attract people to the area');
insert into ideas (title, description) values ('Youn persons live lab','Young people collaborating and networking at live lab - run exactly the same format but for young people POV');
insert into ideas (title, description) values ('Young People involved in city leadership','Delegating young people at all levels of ''city leadership'' - bring young people into key decision making processes - ''think to the future''');
insert into ideas (title, description) values ('Young person to work day','Take a young person to work day - not a baby/child but a YP in need of developing theie mind, and let YP choose where they want to go');
insert into ideas (title, description) values ('Young persons chamber in city council','18-25 year old second chamber in city council (power of veto over the main chamber)');
insert into ideas (title, description) values ('Youth Mentoring','Mentoring for life - targeted at under 30s');
insert into ideas (title, description) values ('Zip wire off the Arts Tower','');
insert into ideas (title, description) values ('''21st century souk market''','Extend the Moor market to stretch all the way to the old castle market, a ''21st century souk''');
insert into ideas (title, description) values ('''Are U Ready'' across city region','''Are U Ready'' rolled out across city region');
insert into ideas (title, description) values ('''Greenway'' routes across, through and around the City, without leaving parkland','');
insert into ideas (title, description) values ('''Ideas Market'' quarter','Create an ''ideas market'' quarter in a regenaration area in the city');
insert into ideas (title, description) values ('''Sheffield collective'' for start ups','');
insert into ideas (title, description) values ('barter.com','barter.com - trade swapping / new currency');
insert into ideas (title, description) values ('beer-flavoured ice cream','');
insert into ideas (title, description) values ('big twinning with aspirational cities','');
insert into ideas (title, description) values ('career services for school leavers','develop real career services at schools to incite leavers to Higher education or jobs, supporting SMEs, start ups, etc. Also feeding back what industry/business needs so leavers can be trained accordingly');
insert into ideas (title, description) values ('diversify city centre housing','As well as student flats in the city centre, build OPA flats, family flats and people who don''t fit into a pigeonhole flats');
insert into ideas (title, description) values ('e-voting system','Electronic voting syetem for hyper local democracy - to capture & achieve higher voter turnout -democracy for the future');
insert into ideas (title, description) values ('improve transport links between Leeds, Sheffield and Manchester','');
insert into ideas (title, description) values ('innovative events','Add an innovation aspect to every festival and expo so that Sheffield becomes the place to launch new tech');
insert into ideas (title, description) values ('intercultural festival','Bringing different ages, races, religions and people together');
insert into ideas (title, description) values ('using empty real estate in city centre','Council & …. empty properties in city centre offered to social enterprises to run cafes, business centres & start up hubs');
insert into ideas (title, description) values ('vibrant Sheffield campaign','A #VibrantSheffield communication campaign that is owned by everyone + is crowd-developed to promote + sell a fresh brand for Sheffield. Harness the passion + ideas today to mobilise a media campaign to promote the city');
insert into ideas (title, description) values ('when travelling into Sheffield, make the ''welcome to'' signs bolder, more appealing and illustrative of what Sheffield can offer','');
